export const TAX_CALCULATION_FETCH = "TAX_CALCULATION_FETCH"
export const TAX_CALCULATION_FETCH_CANCEL = "TAX_CALCULATION_FETCH_CANCEL"
export const TAX_CALCULATION_FETCH_SUCCESS = "TAX_CALCULATION_FETCH_SUCCESS"
export const TAX_CALCULATION_FETCH_FAILED = "TAX_CALCULATION_FETCH_FAILED"
