export const TAX_SPENDING_FETCH = "TAX_SPENDING_FETCH";
export const TAX_SPENDING_FETCH_CANCEL = "TAX_SPENDING_FETCH_CANCEL"
export const TAX_SPENDING_FETCH_SUCCESS = "TAX_SPENDING_FETCH_SUCCESS"
export const TAX_SPENDING_FETCH_FAILED = "TAX_SPENDING_FETCH_FAILED"